version: "2.2"
services:
  db:
    image: postgres:12
    container_name: communa_db
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=db_password
    restart: unless-stopped

  webapp:
    build: .
    container_name: communa_web
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=db_password
      - FILLER_ACCESS_TOKEN=d253377f0f48c9c972228fb3719b8f4e
    depends_on:
      - db
    links:
      - db